pipeline {
    agent any
    stages {
        stage('Create builds') {
            steps {
                jobDsl targets: 'seed-jobs/Jenkins.jobdsl', removedJobAction: 'DELETE'
            }
        }
    }
}